In [83]:
import pandas as pd
import numpy as np

In [84]:
data_processed = pd.read_csv('Absenteeism_preprocessed.csv')

In [85]:
data_processed.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month_val  Day_val  
0         2     1                          4          7        1  
1         1     0                          0          7        1  
2         0     0                          2          7        2  
3         2     0                          4          7        3  
4         2     1                          2          7        3

In [86]:
df = data_processed.copy()

In [87]:
df['Absenteeism Time in Hours'].median()

3.0

In [88]:
tar = np.where(df['Absenteeism Time in Hours'] > df['Absenteeism Time in Hours'].median(), 1,0)

In [89]:
tar

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [90]:
df['Excess_absenteeism'] = tar

In [91]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month_val  Day_val  \
0         2     1                          4          7        1   
1         1     0                          0          7        1   
2         0     0                          2          7        2   
3         2     0                          4          7        3   
4         2     1                          2          7        3   

   Excess_absenteeism  
0                   1  
1                   0  
2                   0  
3                   1  
4                   0

In [92]:
df = df.drop(['Absenteeism Time in Hours','Date','Distance to Work','Month_val','Daily Work Load Average'], axis = 1)

In [93]:
unscaled_inputs = df.iloc[:,:-1]

In [94]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Day_val'], dtype=object)

In [95]:
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

In [96]:
scaled_inputs = unscaled_inputs.copy()

In [98]:
sc_cols = ['Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Day_val']
feat = scaled_inputs[sc_cols]
scaler = StandardScaler().fit(feat.values)
feat = scaler.transform(feat.values)

In [99]:
scaled_inputs[sc_cols] = feat

In [100]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense       Age  \
0           0         0         0         1                1.005844 -0.536062   
1           0         0         0         0               -1.574681  2.130803   
2           0         0         0         1               -0.654143  0.248310   
3           1         0         0         0                0.854936  0.405184   
4           0         0         0         1                1.005844 -0.536062   
..        ...       ...       ...       ...                     ...       ...   
695         1         0         0         0               -0.654143  0.562059   
696         1         0         0         0                0.040034 -1.320435   
697         1         0         0         0                1.624567 -1.320435   
698         0         0         0         1                0.190942 -0.692937   
699         0         0         0         1                1.036026  0.562059   

     Body Mass Index  Education  Children      Pets   Day_val  
0           0.767431  -0.447980  0.880469  0.268487 -0.683704  
1           1.002633  -0.447980 -0.019280 -0.589690 -0.683704  
2           1.002633  -0.447980 -0.919030 -0.589690 -0.007725  
3          -0.643782  -0.447980  0.880469 -0.589690  0.668253  
4           0.767431  -0.447980  0.880469  0.268487  0.668253  
..               ...        ...       ...       ...       ...  
695        -1.114186   2.232242  0.880469 -0.589690 -0.007725  
696        -0.643782  -0.447980 -0.019280  1.126663 -0.007725  
697        -0.408580   2.232242 -0.919030 -0.589690  0.668253  
698        -0.408580   2.232242 -0.919030 -0.589690  0.668253  
699        -0.408580  -0.447980 -0.019280  0.268487  0.668253  

[700 rows x 11 columns]

In [101]:
scaled_inputs.shape

(700, 11)

In [102]:
from sklearn.model_selection import train_test_split

In [103]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, tar, train_size = 0.8, random_state=42)

In [104]:
x_train.shape

(560, 11)

In [105]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [106]:
reg = LogisticRegression()

In [107]:
reg.fit(x_train,y_train)

LogisticRegression()

In [108]:
reg.score(x_train,y_train)

0.7678571428571429

In [109]:
outputs = reg.predict(x_train)

In [110]:
outputs

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,

In [111]:
np.sum(outputs == y_train)/outputs.shape[0]

0.7678571428571429

In [112]:
reg.intercept_

array([-1.7323059])

In [113]:
reg.coef_

array([[ 2.90752099,  0.72678845,  3.05287888,  0.96139258,  0.67233188,
        -0.24764785,  0.24003338, -0.09081923,  0.42183352, -0.31504151,
        -0.15890631]])

In [114]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Day_val'], dtype=object)

In [115]:
summary = pd.DataFrame(columns = ['Feature'], data = unscaled_inputs.columns.values)

In [116]:
summary['Coeffs'] = np.transpose(reg.coef_)

In [117]:
display(summary)

Feature    Coeffs
0                 Reason_1  2.907521
1                 Reason_2  0.726788
2                 Reason_3  3.052879
3                 Reason_4  0.961393
4   Transportation Expense  0.672332
5                      Age -0.247648
6          Body Mass Index  0.240033
7                Education -0.090819
8                 Children  0.421834
9                     Pets -0.315042
10                 Day_val -0.158906

In [118]:
 summary.index += 1

In [119]:
summary.loc[0] = ['Intercept', reg.intercept_[0]]
summary = summary.sort_index()

In [120]:
summary

Feature    Coeffs
0                Intercept -1.732306
1                 Reason_1  2.907521
2                 Reason_2  0.726788
3                 Reason_3  3.052879
4                 Reason_4  0.961393
5   Transportation Expense  0.672332
6                      Age -0.247648
7          Body Mass Index  0.240033
8                Education -0.090819
9                 Children  0.421834
10                    Pets -0.315042
11                 Day_val -0.158906

In [121]:
summary['Odds_ratio'] = np.exp(summary['Coeffs'])

In [122]:
summary.sort_values('Odds_ratio', ascending=False)

Feature    Coeffs  Odds_ratio
3                 Reason_3  3.052879   21.176221
1                 Reason_1  2.907521   18.311348
4                 Reason_4  0.961393    2.615336
2                 Reason_2  0.726788    2.068427
5   Transportation Expense  0.672332    1.958800
9                 Children  0.421834    1.524755
7          Body Mass Index  0.240033    1.271292
8                Education -0.090819    0.913183
11                 Day_val -0.158906    0.853076
6                      Age -0.247648    0.780635
10                    Pets -0.315042    0.729759
0                Intercept -1.732306    0.176876

In [123]:
reg.score(x_test,y_test)

0.7785714285714286

In [125]:
predict_proba = reg.predict_proba(x_test)

In [126]:
#saving the model
import pickle

In [127]:
with open('model', 'wb') as file:
    pickle.dump(reg,file)

In [128]:
with open('scaler', 'wb') as file:
    pickle.dump(scaler,file)